export const ALBUMS = [
    {
        id: 0,
        name: "Endless Beginning EP",
        artist: "Bakkar",
        image: "../src/images/albums/Bakkar-Endless-Beginning-EP-Billegal-Beats.jpeg",
    },
    {
        id: 1,
        name: "Everything Is Wrong EP",
        artist: "ZZY",
        image: "../src/images/albums/ZZY-Everything-Is-Wrong.jpeg",
    },
    {
        id: 2,
        name: "Dozo Sol EP",
        artist: "Fennec III",
        image: "../src/images/albums/Fennec-III-Dozo-Sol.jpeg",
    },
    {
        id: 3,
        name: "The Edge Of Chaos EP",
        artist: "Musin",
        image: "../src/images/albums/Musin-The-Edge-Of-Chaos-EP.jpeg",
    },
    {
        id: 4,
        name: "Hyver EP",
        artist: "Le Perche Oreille",
        image: "../src/images/albums/Le-Perche-Oreille-Hyver-EP.jpeg",
    },
    {
        id: 5,
        name: "Glitch In The Climate EP",
        artist: "Sorcinet",
        image: "../src/images/albums/Sorcinet-Glitch-In-The-Climate.jpeg",
    },
    {
        id: 6,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 7,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 8,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 9,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 10,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 11,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 12,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 13,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 14,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 15,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 16,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 17,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 18,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 19,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 20,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 21,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 22,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    },
    {
        id: 23,
        name: "",
        artist: "",
        image: "../src/images/albums/",
    }
];